name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos:   [windows, linux]
        goarch: [amd64, arm64]
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Build
      id: build
      uses: coalaura/build@v1
      with:
        os: ${{ matrix.goos }}
        arch: ${{ matrix.goarch }}
        optimization: compatible
        generate: false
        output: dist/getup_${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
        go-flags: |
          -ldflags=-X main.Version=${{ github.ref_name }}

    - name: Sign
      id: sign
      uses: coalaura/sign@v1
      with:
        path: ${{ steps.build.outputs.path }}
        key: ${{ secrets.COALAURA_PFX }}
        passphrase: ${{ secrets.COALAURA_PFX_PASSWORD }}
        chain: |
          https://wiese2.org/pki/issuing.pem
          https://wiese2.org/pki/root.pem

    - name: Upload signed artifact
      uses: actions/upload-artifact@v7
      with:
        name: signed-getup_${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }}
        path: ${{ steps.sign.outputs.path }}
        if-no-files-found: error
        retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Download signed artifacts
      uses: actions/download-artifact@v8
      with:
        pattern: signed-getup_*
        path: dist
        merge-multiple: true

    - name: Create GitHub release
      uses: softprops/action-gh-release@v3
      with:
        files: dist/*
        name: "Release ${{ github.ref_name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
